### ISSUE TITLE
Problems with Harlowe 3.0.0

### ISSUE THREAD

**Issue by lpmwfx** [avapoet/twee2#47]
When I try to use the newest Harlowe story format on Twee2 I get the error below. It is Harlowe 3.0 I am trying to use downloaded from https://bitbucket.org/_L_/harlowe/overview
Twee2 works fine with the building Harlowe 1.0.1 format, but as a newbie to Twee2, Twine and the whole IF concepts I wanted to have the latest versions to be sure it works. 

//LarsPM
@lpmwfx

```
> C:\Users\DKMATHIASENL\Documents\Scree Scrivener TWINE TWEE2>twee2 build firstdraft5.txt fd6.html --format=c:\twee2\harlowe3
> Traceback (most recent call last):
>         12: from C:/Ruby25-x64/bin/twee2:23:in `<main>'
>         11: from C:/Ruby25-x64/bin/twee2:23:in `load'
>         10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/twee2-0.5.0/bin/twee2:45:in `<top (required)>'
>          9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
>          8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
>          7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
>          6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
>          5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/twee2-0.5.0/bin/twee2:13:in `build'
>          4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/twee2-0.5.0/lib/twee2.rb:23:in `build'
>          3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/twee2-0.5.0/lib/twee2.rb:23:in `new'
>          2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/twee2-0.5.0/lib/twee2/story_format.rb:14:in `initialize'
>          1: from C:/Ruby25-x64/lib/ruby/2.5.0/json/common.rb:156:in `parse'
> C:/Ruby25-x64/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '{"source":"","}' (JSON::ParserError)
```

**Comment by VegetarianZombie** [comment]
You have to build the Harlowe project and move the compiled library into the twee2 story formats subfolder. Instructions are added at the bottom of the readme.
